version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: undercar_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: REDACTED_DB_PASSWORD
      POSTGRES_DB: monitor_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: