"""Criando tabela de historico de eventos

Revision ID: 69d719de9869
Revises: 87c3fadc5518
Create Date: 2026-05-04 13:55:27.960638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69d719de9869'
down_revision: Union[str, Sequence[str], None] = '87c3fadc5518'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('server_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('server_name', sa.String(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_server_events_id'), 'server_events', ['id'], unique=False)
    op.create_index(op.f('ix_server_events_server_name'), 'server_events', ['server_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_server_events_server_name'), table_name='server_events')
    op.drop_index(op.f('ix_server_events_id'), table_name='server_events')
    op.drop_table('server_events')
    # ### end Alembic commands ###
