"""Adicionando colunas de metricas de CPU e RAM

Revision ID: 87c3fadc5518
Revises: 4c19dce069b7
Create Date: 2026-05-04 12:04:38.365884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87c3fadc5518'
down_revision: Union[str, Sequence[str], None] = '4c19dce069b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('server_states', sa.Column('cpu_usage', sa.Float(), nullable=True))
    op.add_column('server_states', sa.Column('ram_usage', sa.Float(), nullable=True))
    op.add_column('server_states', sa.Column('gpu_usage', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('server_states', 'gpu_usage')
    op.drop_column('server_states', 'ram_usage')
    op.drop_column('server_states', 'cpu_usage')
    # ### end Alembic commands ###
